Repository openshift/cluster-api-provider-ovirt, pull requests merged in 2020-01, with the labels that each got.

#1 Add OWNERS file
  OWNERS
Labels: size/XS

#3 Advertize module path as openshift/cluster-api-provider-ovirt
  cmd/manager/main.go
  go.mod
  pkg/apis/apis.go
  pkg/apis/ovirtprovider/v1beta1/register.go
  pkg/cloud/ovirt/clients/machineservice.go
  pkg/cloud/ovirt/machine/actuator.go
Labels: size/S

#36 Change image to build FROM openshift/origin-v4.0:base in Dockerfile
  Dockerfile
Labels: approved, lgtm, size/XS
