Repository openshift/cluster-api-provider-ovirt, pull requests merged in 2020-07, with the labels that each got.

#53 Bug 1817853: Reconcile network addresses according to VM status
  go.sum
  pkg/apis/ovirtprovider/v1beta1/register.go
  pkg/cloud/ovirt/clients/machineservice.go
  pkg/cloud/ovirt/clients/machineservice_test.go
  pkg/cloud/ovirt/machine/actuator.go
  pkg/cloud/ovirt/machine/instancestatus.go
  pkg/cloud/ovirt/types.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#55 Implement leader election for manager
  cmd/manager/main.go
Labels: approved, lgtm

#56 BUG 1858400: [Performance] Lease refresh period for machine-api-controllers is too high, causes heavy writes to etcd at idle
  cmd/manager/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#60 Metrics port change to support updated MAO metrics integration
  cmd/manager/main.go
Labels: approved, lgtm

#57 Update OWNERS
  OWNERS
Labels: approved, lgtm

#61 Add controller to reconcile node's providerID
  cmd/manager/main.go
  go.mod
  pkg/cloud/ovirt/providerIDcontroller/providerIDController.go
  pkg/cloud/ovirt/providerIDcontroller/providerIDController_test.go
  vendor/k8s.io/klog/klogr/README.md
  vendor/k8s.io/klog/klogr/klogr.go
  vendor/modules.txt
Labels: approved, lgtm
