Repository openshift/cluster-api-provider-ovirt, pull requests merged in 2020-09, with the labels that each got.

#58 Update OWNERS
  OWNERS
Labels: approved, cherry-pick-approved, lgtm

#67 Bug 1872080: Add Dockerfile.rhel to match build configuration in ocp-build-data
  Dockerfile.rhel
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#68 Bug 1864352: Add leader election mechanism to release 4.5
  cmd/manager/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
