Repository openshift/cluster-api-provider-ovirt, pull requests merged in 2021-02, with the labels that each got.

#87 Bug 1926346: move to go 1.15 and registry.ci.openshift.org
  Dockerfile
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#88 add custom capo readme
  docs/custom-capo.md
Labels: approved

#94 credentials: handle error in the strconv.Parsebool
  pkg/cloud/ovirt/clients/credentials.go
Labels: approved, lgtm

#85 Bug 1920905: extract node machine ipaddress from the engine instead using DNS .
  go.mod
  pkg/cloud/ovirt/clients/machineservice.go
  pkg/cloud/ovirt/machine/actuator.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
